### ISSUE TITLE
Invitation to give a talk at PRIDE workshop ECOOP 2022

### ISSUE THREAD

**Issue by linghuiluo** [goblint/GobPie#18]
Dear creators of GobPie,

as an organizer of the PRIDE workshop at ECOOP 2022 (see https://2022.ecoop.org/home/pride-2022#About), I am now looking for talks that fit well into the workshop. 
As you used MagpieBridge to integrate Goblint into IDEs, I'd love to invite you to give a talk about it. 
Here is the call for talks: https://2022.ecoop.org/home/pride-2022#Call-for-Talks.  I'd be very happy to host you as a speaker at the workshop.

Please let me know if you are open for a zoom meeting regarding this invitation and whom I should contact.

Best,
Linghui

**Comment by vesalvojdani** [comment]
Thank you for the invitation.  It would great if you can Zoom meet directly with @karoliineh (Uni Tartu) and @jerhard (TU München). They can coordinate with the rest of us. I will send you an e-mail with their e-mails.
