### ISSUE TITLE
Workspace corruption ...

### ISSUE THREAD

**Issue by vesalvojdani** [goblint/GobPie#30]
This is hard to reproduce, but I fear it can happen to others as well. It's possible to corrupt the workspace such that Goblint refuses to analyze with GobPie, but it works if one moves to folder. And then it does not work if one moves it back. (Restarting the computer does not help.) There is some persistent state held onto by VC Code. It seems one of the solutions [here](https://stackoverflow.com/questions/53015284/how-can-i-cleanly-remove-workspaces-in-visual-studio-code/59896610#59896610) worked for me. I think it was simply to do file -> close folder. Amazing stuff.

**Comment by FeldrinH** [comment]
This is already marked as wontfix and without a reproduction there doesn't really seem to be anything actionable, so this should probaly be closed?
